### ISSUE TITLE
ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by noobmanioh** [IAHispano/Applio-Installer#19]
hello i just start the program and try to use the applio
![image](https://github.com/IAHispano/Applio-Installer/assets/95874311/d079205b-e5a7-4d97-b47d-51e90b54ea59)
and it's said
Starting Applio-RVC-Fork with Conda for AMD specific support...
Traceback (most recent call last):
  File "C:\Users\Ryzen X Redeon\Desktop\Applio-RVC-Fork\Applio-RVC-Fork\infer-web.py", line 13, in <module>
    from assets.configs.config import Config
  File "C:\Users\Ryzen X Redeon\Desktop\Applio-RVC-Fork\Applio-RVC-Fork\assets\configs\config.py", line 10, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Press any key to continue . . .
i try many times and try reinstall the applio

**Comment by blaise-tk** [comment]
Install using the first option.
